<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class ContentSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'Аніме' => ['en' => 'Anime', 'de' => 'Anime'],
            'Відеоігри' => ['en' => 'Video Games', 'de' => 'Videospiele'],
            'Хорор' => ['en' => 'Horror', 'de' => 'Horror'],
            'Комікси' => ['en' => 'Comics', 'de' => 'Comics'],
        ];

        foreach ($categories as $name => $trans) {
            Category::updateOrCreate(
                ['slug' => Str::slug($trans['en'])],
                [
                    'name' => $name,
                    'name_en' => $trans['en'],
                    'name_de' => $trans['de'],
                ]
            );
        }

        $animeId = Category::where('name_en', 'Anime')->first()->id;
        $gamesId = Category::where('name_en', 'Video Games')->first()->id;
        $horrorId = Category::where('name_en', 'Horror')->first()->id;

        $artbooks = [
            [
                'name' => 'Артбук Зоревир: Крізь всесвіт',
                'name_en' => 'Artbook Zorevyr: Across the Universe',
                'name_de' => 'Artbook Zorevyr: Durch das Universum',
                'author' => 'Zorevyr Studio',
                'description' => 'Артбук з українського фантастичного світу Зоревир з ілюстраціями космічних подорожей.',
                'description_en' => 'Artbook from the Ukrainian fantasy world Zorevyr with illustrations of cosmic journeys.',
                'description_de' => 'Artbook aus der ukrainischen Fantasywelt Zorevyr mit Illustrationen kosmischer Reisen.',
                'price' => 900.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 224,
            ],
            [
                'name' => 'Лорбук NieR: Automata. Путівник світом',
                'name_en' => 'Lorebook NieR: Automata World Guide',
                'name_de' => 'Lorebook NieR: Automata Weltführer',
                'author' => 'Square Enix',
                'description' => 'Офіційний лорбук з детальною хронологією, персонажами та таємницями світу NieR: Automata.',
                'description_en' => 'Official lorebook with detailed chronology, characters and secrets of the world of NieR: Automata.',
                'description_de' => 'Offizielles Lorebuch mit detaillierter Chronologie, Charakteren und Geheimnissen der Welt von NieR: Automata.',
                'price' => 1200.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 256,
            ],
            [
                'name' => 'Артбук Українська магічна академія (Делюкс-видання)',
                'name_en' => 'Artbook Ukrainian Magic Academy (Deluxe Edition)',
                'name_de' => 'Artbook Ukrainische Magische Akademie (Deluxe-Ausgabe)',
                'author' => 'Ukrainian Magic Academy',
                'description' => 'Розширене делюкс-видання з додатковими ілюстраціями, ескізами та локаціями чарівної академії.',
                'description_en' => 'Extended deluxe edition with additional illustrations, sketches and locations of the magical academy.',
                'description_de' => 'Erweiterte Deluxe-Ausgabe mit zusätzlichen Illustrationen, Skizzen und Schauplätzen der magischen Akademie.',
                'price' => 1200.00,
                'stock' => 8,
                'category_id' => $animeId,
                'pages' => 280,
            ],
            [
                'name' => 'Артбук Українська магічна академія (Базове видання)',
                'name_en' => 'Artbook Ukrainian Magic Academy (Standard Edition)',
                'name_de' => 'Artbook Ukrainische Magische Akademie (Standardausgabe)',
                'author' => 'Ukrainian Magic Academy',
                'description' => 'Базове видання артбуку зі світу Української магічної академії з ключовими ілюстраціями.',
                'description_en' => 'Standard edition artbook from the world of the Ukrainian Magical Academy with key illustrations.',
                'description_de' => 'Standardausgabe des Artbooks aus der Welt der ukrainischen magischen Akademie mit wichtigen Illustrationen.',
                'price' => 800.00,
                'stock' => 12,
                'category_id' => $animeId,
                'pages' => 220,
            ],
            [
                'name' => 'Артбук Химерні візії. Збірка ілюстрацій Джюнджі Іто',
                'name_en' => 'Artbook Twisted Visions: Junji Ito Illustrations',
                'name_de' => 'Artbook Verdrehte Visionen: Junji Ito Illustrationen',
                'author' => 'Джюнджі Іто',
                'description' => 'Колекція моторошних і водночас витончених ілюстрацій від майстра японського хорору.',
                'description_en' => 'A collection of eerie yet exquisite illustrations from the master of Japanese horror.',
                'description_de' => 'Eine Sammlung unheimlicher und zugleich feiner Illustrationen des Meisters des japanischen Horrors.',
                'price' => 1200.00,
                'stock' => 6,
                'category_id' => $horrorId,
                'pages' => 240,
            ],
            [
                'name' => 'Артбук Світ гри Death Stranding 2: On the Beach',
                'name_en' => 'Art of Death Stranding 2: On the Beach',
                'name_de' => 'Die Kunst von Death Stranding 2: On the Beach',
                'author' => 'Kojima Productions',
                'description' => 'Офіційний артбук до гри Death Stranding 2 з концептами персонажів, локацій та техніки.',
                'description_en' => 'Official artbook for Death Stranding 2 featuring concepts of characters, locations and technology.',
                'description_de' => 'Offizielles Artbook zu Death Stranding 2 mit Konzepten von Charakteren, Schauplätzen und Technik.',
                'price' => 1200.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 256,
            ],
            [
                'name' => 'Ілюстрована книга Mofusand. Робочі будні Нявкобратиків',
                'name_en' => 'Illustrated Book Mofusand: Workdays of Nyako Brothers',
                'name_de' => 'Illustriertes Buch Mofusand: Arbeitsalltag der Nyako-Brüder',
                'author' => 'Jian',
                'description' => 'Милий ілюстрований щоденник котиків Mofusand про їхні кумедні робочі будні.',
                'description_en' => 'Cute illustrated diary of Mofusand cats about their funny workdays.',
                'description_de' => 'Süßes illustriertes Tagebuch der Mofusand-Katzen über ihren lustigen Arbeitsalltag.',
                'price' => 250.00,
                'stock' => 20,
                'category_id' => $animeId,
                'pages' => 112,
            ],
            [
                'name' => 'Артбук Мистецтво й створення серіалу «Аркейн»',
                'name_en' => 'The Art of Arcane',
                'name_de' => 'Die Kunst von Arcane',
                'author' => 'Riot Games',
                'description' => 'Закулісний погляд на створення анімаційного серіалу «Аркейн» з ескізами, кадрами та концепт-артом.',
                'description_en' => 'Behind-the-scenes look at the creation of the animated series Arcane with sketches, frames and concept art.',
                'description_de' => 'Ein Blick hinter die Kulissen der Entstehung der Animationsserie Arcane mit Skizzen, Frames und Concept Art.',
                'price' => 1290.00,
                'stock' => 10,
                'category_id' => $animeId,
                'pages' => 264,
            ],
            [
                'name' => 'Артбук Світ гри S.T.A.L.K.E.R. 2: Heart of Chornobyl',
                'name_en' => 'The World of S.T.A.L.K.E.R. 2: Heart of Chornobyl',
                'name_de' => 'Die Welt von S.T.A.L.K.E.R. 2: Heart of Chornobyl',
                'author' => 'GSC Game World',
                'description' => 'Артбук зі світу S.T.A.L.K.E.R. 2 з локаціями Зони, мутантами та спорядженням сталкерів.',
                'description_en' => 'Artbook from the world of S.T.A.L.K.E.R. 2 with Zone locations, mutants and stalker gear.',
                'description_de' => 'Artbook aus der Welt von S.T.A.L.K.E.R. 2 mit Zonen-Schauplätzen, Mutanten und Ausrüstung der Stalker.',
                'price' => 1200.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 256,
            ],
            [
                'name' => 'Артбук Євангеліон. Збірка ілюстрацій 2007–2017',
                'name_en' => 'Evangelion Illustration Collection 2007–2017',
                'name_de' => 'Evangelion Illustrationssammlung 2007–2017',
                'author' => 'Khara',
                'description' => 'Добірка офіційних ілюстрацій з франшизи Evangelion за десятирічний період.',
                'description_en' => 'Selection of official illustrations from the Evangelion franchise over a decade.',
                'description_de' => 'Auswahl offizieller Illustrationen aus dem Evangelion-Franchise über ein Jahrzehnt.',
                'price' => 950.00,
                'stock' => 10,
                'category_id' => $animeId,
                'pages' => 232,
            ],
            [
                'name' => 'Лорбук God of War: Перекази й легенди',
                'name_en' => 'Lorebook God of War: Myths and Legends',
                'name_de' => 'Lorebook God of War: Sagen und Legenden',
                'author' => 'Santa Monica Studio',
                'description' => 'Лорбук з міфами, легендами та історіями світу God of War.',
                'description_en' => 'Lorebook with myths, legends and stories from the world of God of War.',
                'description_de' => 'Lorebuch mit Mythen, Legenden und Geschichten aus der Welt von God of War.',
                'price' => 795.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 208,
            ],
            [
                'name' => 'Артбук Bloodborne: Офіційні ілюстрації',
                'name_en' => 'Bloodborne: Official Artworks',
                'name_de' => 'Bloodborne: Offizielle Illustrationen',
                'author' => 'FromSoftware',
                'description' => 'Офіційна колекція ілюстрацій і концепт-артів похмурого міста Ярнам.',
                'description_en' => 'Official collection of illustrations and concept art of the grim city of Yharnam.',
                'description_de' => 'Offizielle Sammlung von Illustrationen und Concept Art der düsteren Stadt Yharnam.',
                'price' => 1200.00,
                'stock' => 8,
                'category_id' => $gamesId,
                'pages' => 256,
            ],
            [
                'name' => 'Артбук Ігровий світ трилогії Total War: Warhammer',
                'name_en' => 'Game World of Total War: Warhammer Trilogy',
                'name_de' => 'Spielwelt der Total War: Warhammer Trilogie',
                'author' => 'Creative Assembly',
                'description' => 'Артбук, присвячений фракціям, битвам і ландшафтам світу Total War: Warhammer.',
                'description_en' => 'Artbook dedicated to factions, battles and landscapes of the Total War: Warhammer world.',
                'description_de' => 'Artbook über Fraktionen, Schlachten und Landschaften der Welt von Total War: Warhammer.',
                'price' => 1200.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 272,
            ],
            [
                'name' => 'Артбук Світ гри Horizon Zero Dawn',
                'name_en' => 'The World of Horizon Zero Dawn',
                'name_de' => 'Die Welt von Horizon Zero Dawn',
                'author' => 'Guerrilla Games',
                'description' => 'Ілюстрований довідник зі світу Horizon Zero Dawn з машинами та племенами.',
                'description_en' => 'Illustrated guide to the world of Horizon Zero Dawn with machines and tribes.',
                'description_de' => 'Illustrierter Führer durch die Welt von Horizon Zero Dawn mit Maschinen und Stämmen.',
                'price' => 950.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 224,
            ],
            [
                'name' => 'Артбук Світ гри Far Cry 6',
                'name_en' => 'The World of Far Cry 6',
                'name_de' => 'Die Welt von Far Cry 6',
                'author' => 'Ubisoft',
                'description' => 'Артбук, присвячений світу Яри, її революції та харизматичним персонажам.',
                'description_en' => 'Artbook dedicated to the world of Yara, its revolution and charismatic characters.',
                'description_de' => 'Artbook über die Welt von Yara, ihre Revolution und charismatische Charaktere.',
                'price' => 810.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 208,
            ],
            [
                'name' => 'Артбук Український бестіарій',
                'name_en' => 'Ukrainian Bestiary Artbook',
                'name_de' => 'Ukrainischer Bestiarium Artbook',
                'author' => 'Ukrainian Artists',
                'description' => 'Збірка ілюстрацій українських міфологічних істот у сучасній подачі.',
                'description_en' => 'Collection of illustrations of Ukrainian mythological creatures in a modern style.',
                'description_de' => 'Sammlung von Illustrationen ukrainischer mythologischer Kreaturen in modernem Stil.',
                'price' => 800.00,
                'stock' => 12,
                'category_id' => $horrorId,
                'pages' => 200,
            ],
            [
                'name' => 'Артбук Створення світу гри Hogwarts Legacy',
                'name_en' => 'The Art and Making of Hogwarts Legacy',
                'name_de' => 'Die Kunst und Entstehung von Hogwarts Legacy',
                'author' => 'Warner Bros.',
                'description' => 'Офіційний артбук про створення магічного світу гри Hogwarts Legacy.',
                'description_en' => 'Official artbook about the creation of the magical world of Hogwarts Legacy.',
                'description_de' => 'Offizielles Artbook über die Entstehung der magischen Welt von Hogwarts Legacy.',
                'price' => 1200.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 256,
            ],
            [
                'name' => 'Артбук Світ гри God of War',
                'name_en' => 'The World of God of War',
                'name_de' => 'Die Welt von God of War',
                'author' => 'Santa Monica Studio',
                'description' => 'Артбук з описом богів, світів та істот саги God of War.',
                'description_en' => 'Artbook describing gods, worlds and creatures of the God of War saga.',
                'description_de' => 'Artbook mit Beschreibungen von Göttern, Welten und Kreaturen der God of War-Saga.',
                'price' => 650.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 216,
            ],
            [
                'name' => 'Артбук Ігровий світ трилогії Mass Effect',
                'name_en' => 'Game World of the Mass Effect Trilogy',
                'name_de' => 'Spielwelt der Mass Effect Trilogie',
                'author' => 'BioWare',
                'description' => 'Артбук про раси, кораблі та планети всесвіту Mass Effect.',
                'description_en' => 'Artbook about races, ships and planets of the Mass Effect universe.',
                'description_de' => 'Artbook über Rassen, Schiffe und Planeten des Mass Effect-Universums.',
                'price' => 920.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 256,
            ],
            [
                'name' => 'Артбук Світ гри The Last of Us',
                'name_en' => 'The World of The Last of Us',
                'name_de' => 'Die Welt von The Last of Us',
                'author' => 'Naughty Dog',
                'description' => 'Артбук, присвячений атмосфері постапокаліптичного світу The Last of Us.',
                'description_en' => 'Artbook dedicated to the atmosphere of the post-apocalyptic world of The Last of Us.',
                'description_de' => 'Artbook über die Atmosphäre der postapokalyptischen Welt von The Last of Us.',
                'price' => 750.00,
                'stock' => 10,
                'category_id' => $gamesId,
                'pages' => 224,
            ],
        ];

        foreach ($artbooks as $artbook) {
            Product::updateOrCreate(
                ['slug' => Str::slug($artbook['name_en'])],
                array_merge($artbook, ['is_popular' => rand(0, 1), 'is_new' => rand(0, 1)])
            );
        }
    }
}
